### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by Michael-Yap** [MaxTMcCoy/CryptoTickerWidget#4]
How can we get this to work on MAC? Cannot add the additional code to the end of a "LOCAL FILE" filename.

**Comment by MaxTMcCoy** [comment]
@Michael-Yap 
I've made some recent updates that I was waiting to deploy, I just deployed them. 

One of the updates is you no longer need to download any files locally. Just use this url https://maxtmccoy.github.io/CryptoTickerWidget/widget.html?theme=default&coin=dogecoin .

The read me has been updated. Let me know how that works for ya.

**Comment by Michael-Yap** [comment]
Can you help me by making it default to BTC? When I change it, it doesn't work. Also, does the chart show the 1 day prices or what's the timeframe? Thanks for the update!!

**Comment by MaxTMcCoy** [comment]
@Michael-Yap Sure! You just need to change the coin to bitcoin use this: `https://maxtmccoy.github.io/CryptoTickerWidget/widget.html?theme=default&coin=bitcoin` 

The chart shows a bit less than 7 hours of price data, and checks for updates every few seconds.

If this widget/overlay gets more popular I might be able to upgrade the api and make the widget more configureable, So do share it!! I'm excited to see people using it, when you get it up on your stream be sure to link me so I can drop by and say Hi!

Let me know if you need more help!

https://og-miyagi.itch.io/crypto-stream-widget
